### ISSUE TITLE
Get UnicodeDecodeError when pip install django-nvd3 on ubuntu

### ISSUE THREAD

**Issue by zoe-stockholm** [areski/django-nvd3#76]
pip install works on my local but didn't work on ubuntu server no matter which version of django-nvd3.
Django==1.8.2
python-nvd3==0.14.2
python 3.4

ps: It was working before (django-nvd3==0.8.2), today I just upgrade it and run pip unistall and  pip install. Now I can't install django-nvd3 on any version.

  Downloading django-nvd3-0.9.7.tar.gz
  Running setup.py (path:/home/ubuntu/.venv/[project_name]/build/django-nvd3/setup.py) egg_info for package django-nvd3
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/ubuntu/.venv/[project_name]/build/django-nvd3/setup.py", line 7, in <module>
        readme = readme_file.read()
      File "/home/ubuntu/.venv/[project_name]/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2070: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/ubuntu/.venv/[project_name]/build/django-nvd3/setup.py", line 7, in <module>

    readme = readme_file.read()

  File "/home/ubuntu/.venv/[project_name]/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2070: ordinal not in range(128)

**Comment by lgp171188** [comment]
@zoe-stockholm This happens due to issues with locale. See http://stackoverflow.com/a/25575908 for knowing which locale-related environment variables to set.

**Comment by zoe-stockholm** [comment]
Thanks @lgp171188 ! It works for me like a charm!
